!
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    container_name: php_fpm_app
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - infra_central_net

  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "8086:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - infra_central_net

  php-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    container_name: php_cli_app
    volumes:
      - ./src:/app
    working_dir: /app
    env_file:
      - .env
    networks:
      - infra_central_net
    tty: true
    stdin_open: true

networks:
  infra_central_net:
    external: true